# Generated by Django 3.2.5 on 2022-06-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoPresidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('cedula', models.CharField(max_length=10)),
                ('votos', models.IntegerField()),
                ('profesion', models.CharField(max_length=100)),
                ('partido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Propuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=800)),
                ('propuestas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='candidatos.candidatopresidente')),
            ],
        ),
    ]
