# Generated by Django 3.2.5 on 2022-06-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatopresidente',
            name='votos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
